# Generated by Django 5.2.1 on 2025-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_solution_task_example_input_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='example_input',
            new_name='expected_output',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='example_output',
            new_name='input_data',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
