# Generated by Django 5.2.1 on 2025-05-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='input_data',
            field=models.TextField(blank=True),
        ),
    ]
