# Generated by Django 5.2.1 on 2025-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_created_at_alter_task_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_daily_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
