# Generated by Django 5.2.1 on 2025-05-22 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_achievement_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='unlocked_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
